### ISSUE TITLE
When entering link in text, a space is added 

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-portal#175]
In Action text editing, when entering link in text, a space is added after the text with the link, sometimes right after it, sometimes 5 - 12 characters later. Drives our editors nuts :)
Not sure if this is Sam or Frimpong so adding it to both boards.

**Comment by BradHN1** [comment]
This should have been fixed, with the WYSIWYG  change..  Can you try this @kaatvds

**Comment by kaatvds** [comment]
just mentioning that in CAN on  11/8/2020 the space is still an issue, cf. 
![image](https://user-images.githubusercontent.com/30277868/98488115-50b9f380-21f5-11eb-83b2-37ee88366163.png)
