### ISSUE TITLE
Testimonial author displayed name 

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-portal#73]
ISSUE 1210
Reported on Wed Dec 18 2019 19:02:43 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = High
STATUS =  - Submitted 

Site Url: https://sandbox.community.massenergize.org/wayland/testimonials

Description:
sorry my explanation on the testimonial page wasn't clear. When authoring a testimonial, have extra question that is literally: ////// Your name and email will be know to the community organizer. But how would you like your name to be displayed on the site? For instance, "Shelly in Wayland", or  "Anonymous". //////  For a workaround, the Cadmin can add the name the author chose to the bottom of the testimonial.

User Role: Community User

**Comment by kaatvds** [comment]
Hi Frimpong, I didn't mean the user should click "Shelley in Wayland" as an option. That was just an example of what the user would input as their name. 
When authoring a testimonial, have extra question that is literally: ////// Your name and email will be know to the community organizer. But how would you like your name to be displayed on the site? For instance, "Shelly in Wayland", or "Anonymous". ////// That is just the line. **Then give them a way to leave their name.**

**Comment by kaatvds** [comment]
@Pongo1 let's talk about this one

**Comment by kaatvds** [comment]
Works on the form, but I created a testimonial with preferred name "Kaatalyst" and it was not displayed -my full name was displayed...  prob this needs to be squared on database-admin side?

**Comment by kaatvds** [comment]
nope... still not working. The nickname I put in was crazybug but it still shows my full name.

![image](https://user-images.githubusercontent.com/30277868/78934223-8f79a680-7a78-11ea-8274-abe539d267ab.png)

**Comment by ellentohn** [comment]
Allow user to put in a space between first name and last initial -- space should be allowed within the character limit

**Comment by BradHN1** [comment]
Noting that all testimonials in the page for Energize Wayland shown as "Anonymous" on the prod portal.

**Comment by Pongo1** [comment]
Hi @BradHN1, everything appears anonymous because the testimonials were created before we implemented the "anonymous" feature. As such, the testimonials do not have content in their "preferred_name".... that is why.

**Comment by BradHN1** [comment]
This may not be a bug once the testimonial authors are cleaned up.
@OrlyStrobel - can you check this?  @kaatvds @ellentohn

**Comment by OrlyStrobel** [comment]
@BradHN1 seems to be working. Still not sure how to edit authors on old testimonials, but seems to be working as some look anonymous and some have names. Closed issue and moved it to Validating in QA.

**Comment by ellentohn** [comment]
I would if we can ask Sam if there is a way to edit authors. Only other idea is to rewrite them with the authors name and just use their first name and last initial. 

ET

**Comment by BradHN1** [comment]
Authors can be edited in the Dev admin portal, which needs to be deployed in prod

++++++++++++++++++++
Bradley Hubbard-Nelson
221 Nashawtuc Rd
Concord, MA 01742
bradhn@mindspring.com
hubbardnelson.org <http://hubbardnelson.org/>
Tel: 978-505-7128 (cell)
